In [1]:
import pandas as pd

In [3]:
pd.read_csv("../data/FM2024_field_player_info.csv").head()

,Name,Age,Position(s),Foot,Height,Weight,Club,Wages,corners,crossing,...,vision,work-rate,acceleration,agility,balance,jumping-reach,natural-fitness,pace,stamina,strength
0,Kevin De Bruyne,32,"MC, MR, ML, AMCMC, AMC",Right,181 CM,68 KG,Manchester City,"€ 397,800 pw",70,95,...,99,75,80,65,70,50,80,70,80,65
1,Erling Haaland,22,STST,Left,195 CM,94 KG,Manchester City,"€ 397,800 pw",35,50,...,70,65,85,80,85,90,95,95,70,85
2,Kylian Mbappé,24,"AMR, AML, STAML, ST",Right,178 CM,73 KG,PSG,"€ 1,038,960 pw",65,60,...,75,60,99,80,70,40,75,99,70,55
3,Lionel Messi,36,"AMR, AMC, STAMR, AMC, ST",Left,169 CM,67 KG,Inter Miami,"€ 368,240 pw",75,75,...,99,45,80,75,90,30,70,75,65,45
4,Harry Kane,29,"AMC, STST",Right,188 CM,86 KG,FC Bayern,"€ 423,280 pw",45,75,...,95,80,60,60,75,75,80,70,80,75